# basic redirect rules
[[redirects]]
  from = "/carnival"
  to = "https://distrokid.com/hyperfollow/sadlilblackboy/carnival"
  status = 301
  force = false

[[redirects]]
  from = "/merch"
  to = "https://teespring.com/stores/sadlilblackboy"
  status = 301
  force = false
  
[[redirects]]
  from = "/beats"
  to = "https://sadlilblackboy.beatstars.com"
  status = 301
  force = false
  
[[redirects]]
  from = "/want-it-all"
  to = "https://distrokid.com/hyperfollow/nuq/want-it-all"
  status = 301
  force = false
