# basic redirect rules
[[redirects]]
  from = "/carnival"
  to = "https://distrokid.com/hyperfollow/sadlilblackboy/carnival"
  status = 301
  force = false

[[redirects]]
  from = "/merch"
  to = "https://numusic.shop/"
  status = 301
  force = false

[[redirects]]
  from = "/submissions"
  to = "https://www.toneden.io/sadlilblackboy/post/lo-fi-playlist-submissions"
  status = 301
  force = false
  
[[redirects]]
  from = "/beats"
  to = "https://sadlilblackboy.beatstars.com"
  status = 301
  force = false
  
[[redirects]]
  from = "/want-it-all"
  to = "https://distrokid.com/hyperfollow/nuq/want-it-all"
  status = 301
  force = false
  
[[redirects]]
  from = "/lonely-beach"
  to = "https://distrokid.com/hyperfollow/nuq/lonely-beach"
  status = 301
  force = false
  
 [[redirects]]
  from = "/kaleidoscope"
  to = "https://distrokid.com/hyperfollow/sadlilblackboy/kaleidoscope-feat-nuq"
  status = 301
  force = false
  
 [[redirects]]
  from = "/are-we-fine"
  to = "https://distrokid.com/hyperfollow/sadlilblackboy/are-we-fine"
  status = 301
  force = false

 [[redirects]]
  from = "/counting-the-days"
  to = "https://distrokid.com/hyperfollow/sadlilblackboyandnuq/counting-the-days"
  status = 301
  force = false
  
 [[redirects]]
  from = "/put-your-records-on"
  to = "https://distrokid.com/hyperfollow/nuqandjulianachahayed/put-your-records-on-2"
  status = 301
  force = false
  
[[redirects]]
  from = "/human-holiday-2"
  to = "https://distrokid.com/hyperfollow/nuq/human-holiday-2"
  status = 301
  force = false
  
 [[redirects]]
  from = "/monday-mix"
  to = "https://www.toneden.io/sadlilblackboy/post/monday-mix-submission-unlock"
  status = 301
  force = false
